config/routes.rb
Rails.application.routes.draw do
  # routing for admin user
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routing for devise
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Defines the root path route ("/")
  root "home#index"

  # search item
  get '/search', to: 'items#search', as: :search

  # maker list page
  get '/makers', to: 'makers#index', as: :makers

  # item list by category
  get '/categories/:id', to: 'categories#all_items', as: :all_items_by_category

  # item list by maker
  get '/makers/:id', to: 'makers#all_items', as: :all_items_by_maker

  # item detail
  get '/items/:id', to: 'items#show', as: :show_item

  # like item
  post '/items/:id/like', to: 'items#like_item', as: :like_item

  # remove liked item
  post '/items/:id/like/remove', to: 'items#remove_liked_item', as: :remove_liked_item

  # new review form
  get '/items/:id/review/new', to: 'reviews#new', as: :new_review

  # review item
  post '/items/:id/review', to: 'reviews#create', as: :review_item
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # validation
  validates :name, presence: true, length: { maximum: 30 }
end

app/models/item.rb
class Item < ApplicationRecord
  # relation
  belongs_to :category
  belongs_to :maker
  has_many :sales
  has_many :shops, through: :sales
  has_many :likes
  has_many :users, through: :likes
  has_many :reviews
  has_many :rates, through: :reviews, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
  # relation
  belongs_to :user
  belongs_to :item

  # validation
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/maker.rb
class Maker < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  # relation
  belongs_to :user
  belongs_to :item

  # validation
  validates :title,
            presence: true,
            length: { maximum: 50 }
  validates :body,
            presence: true,
            length: { maximum: 300 }
  validates :rate,
             presence: true,
             numericality: {
             less_than_or_equal_to: 5,
             greater_than_or_equal_to: 1}
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/sale.rb
class Sale < ApplicationRecord
  # relation
  belongs_to :item
  belongs_to :shop

  # validation
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 },
  format: { with: /\A[0-9]+\z/ }
  validates :shop_id, uniqueness: { scope: :item_id }
end

app/models/shop.rb
class Shop < ApplicationRecord
  # enum
  enum postage: { 無料: 0, 有料: 1 }
  enum indication: { 受注生産: 0, 在庫: 1 }

  # relation
  has_many :sales
  has_many :items, through: :sales
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # relation
  has_many :likes
  has_many :items, through: :likes
  has_many :reviews
  has_many :rates, through: :reviews, source: :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_q

  def set_q
    @q = Item.ransack(params[:q])
    logger.debug('ここから')
    logger.debug(params[:q])
    logger.debug('ここまで')
    @items = @q.result
    if params[:q].present? && params[:q][:name_or_description_gt].present?
    @search_word = params[:q][:name_or_description_gt]
  end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def all_items
    @items = Item::where(category_id: params[:id])
    @category_name = Category.find(params[:id]).name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: %i(like_item)

  def show
    @item = Item.find(params[:id])
    @shops = @item.sales
  end

  def like_item
    user = current_user
    item = Item.find(params[:id])

    user.items << item
    redirect_to request.referer, notice: 'お気に入りに追加しました'
  end

  def remove_liked_item
    res = Like.where(item_id: params[:id]).find_by(user_id: current_user.id)
    res.destroy

    redirect_to request.referer, notice: 'お気に入りを解除しました'
  end

  def search
  end
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  def index
    @makers = Maker.all
  end

  def all_items
    @items = Item::where(maker_id: params[:id])
    @maker_name = Maker.find(params[:id]).name
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_item
  before_action :init_review

  def new
  end

  def create
    user = current_user
    item = Item.find(params[:id])

    @review = Review.new(review_params)
    @review.user_id = user.id
    @review.item_id = item.id

    if @review.save
      redirect_to show_item_path(item), notice: 'レビューを投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end


  # private
  def review_params
    params.require(:review).permit(:title, :body, :rate)
  end

  def find_item
    @item = Item.find(params[:id])
  end

  def init_review
    @review = Review.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "【価格.com】".freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{BASE_TITLE} - #{page_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def check_controller
    controller_name == 'home'
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def check_liked(item_id)
    item = Item.find(item_id)
    res = item.likes.where(user_id: current_user)

    res.any?
  end

  def get_star(rate)
    image_tag('ico_star_active.png', class: "ico") * rate
  end
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: '' } %>

<!-- flash message -->
<%= render 'shared/flash_message' %>

<%= search_form_for @q, url: search_path, method: :get, class: 'search-form flex' do |search| %>
<%= search.search_field :name_or_description_gt, class: 'search-form__input--search', placeholder: '何をお探しですか？（製品名、説明）' %>
<%= search.submit '検索', class: 'search-form__input--submit' %>
<% end %>

<ul class="home-list flex">
  <% @categories.each do |category| %>
  <%= link_to all_items_by_category_path(category), class: 'contents' do %>
  <li class="home-list__item flex">
    <%= image_tag 'ico_category.jpg', class: 'home-list__item-ico' %>
    <p class="home-list__item-txt"><%= category.name %></p>
  </li>
  <% end %>
  <% end %>
</ul>

<ul class="home-links flex">
  <li class="home-links__item">
    <%= link_to 'メッセージ', '#' %>
  </li>
  <li class="home-links__item">
    <%= link_to '掲載情報について', '#' %>
  </li>
  <li class="home-links__item">
    <%= link_to '利用規約', '#' %>
  </li>
  <li class="home-links__item">
    <%= link_to '個人情報保護方針', '#' %>
  </li>
  <li class="home-links__item">
    <%= link_to 'サイトマップ', '#' %>
  </li>
  <li class="home-links__item">
    <%= link_to 'メーカー一覧', makers_path %>
  </li>
  <li class="home-links__item">
    <%= link_to 'お問い合わせ', '#' %>
  </li>
</ul>

app/views/reviews/new.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: @item.name + 'のレビュー投稿' } %>

<h2 class="basic-heading"><%= @item.name %>のレビュー</h2>

<%= form_with model: @review, url: review_item_path(@item), class: 'review-form' do |new_review| %>

<!-- error message -->
<% if @review.errors.any? %>
<div id="error_explanation">
  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<table class="review-form__table">
  <tbody>
    <tr>
      <th>題名</th>
      <td>
        <%= new_review.text_field :title, autofocus: true, autocomplete: "title", class: 'review-form__table-input' %>
      </td>
    </tr>
    <tr>
      <th>内容</th>
      <td>
        <%= new_review.text_area :body, autofocus: true, autocomplete: "body", class: 'review-form__table-textarea', rows: 5 %>
      </td>
    </tr>
    <tr>
      <th>評価</th>
      <td>
        <%= new_review.select :rate, [1, 2, 3, 4, 5], {include_blank: '評価を選択してください'}, class: 'review-form__table-select' %>
      </td>
    </tr>
  </tbody>
</table>
<%= new_review.submit "投稿", class: 'review-form__table-input--submit' %>
<% end %>