config/routes.rb
Rails.application.routes.draw do
  # routing for admin user
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routing for devise
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Defines the root path route ("/")
  root "home#index"

  # search item
  get '/search', to: 'items#search', as: :search

  # maker list page
  get '/makers', to: 'makers#index', as: :makers

  # item list by category
  get '/categories/:id', to: 'categories#all_items', as: :all_items_by_category

  # item list by maker
  get '/makers/:id', to: 'makers#all_items', as: :all_items_by_maker

  # item detail
  get '/items/:id', to: 'items#show', as: :show_item

  # like item
  post '/items/:id/like', to: 'items#like_item', as: :like_item

  # remove liked item
  post '/items/:id/like/remove', to: 'items#remove_liked_item', as: :remove_liked_item

  # new review form
  get '/items/:id/review/new', to: 'reviews#new', as: :new_review

  # review item
  post '/items/:id/review', to: 'reviews#create', as: :review_item
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # validation
  validates :name, presence: true, length: { maximum: 30 }
end

app/models/item.rb
class Item < ApplicationRecord
  # relation
  belongs_to :category
  belongs_to :maker
  has_many :sales
  has_many :shops, through: :sales
  has_many :likes
  has_many :users, through: :likes
  has_many :reviews
  has_many :rates, through: :reviews, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
  # relation
  belongs_to :user
  belongs_to :item

  # validation
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/maker.rb
class Maker < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  # relation
  belongs_to :user
  belongs_to :item

  # validation
  validates :title,
            presence: true,
            length: { maximum: 50 }
  validates :body,
            presence: true,
            length: { maximum: 300 }
  validates :rate,
             presence: true,
             numericality: {
             less_than_or_equal_to: 5,
             greater_than_or_equal_to: 1}
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/sale.rb
class Sale < ApplicationRecord
  # relation
  belongs_to :item
  belongs_to :shop

  # validation
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 },
  format: { with: /\A[0-9]+\z/ }
  validates :shop_id, uniqueness: { scope: :item_id }
end

app/models/shop.rb
class Shop < ApplicationRecord
  # enum
  enum postage: { 無料: 0, 有料: 1 }
  enum indication: { 受注生産: 0, 在庫: 1 }

  # relation
  has_many :sales
  has_many :items, through: :sales
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # relation
  has_many :likes
  has_many :items, through: :likes
  has_many :reviews
  has_many :rates, through: :reviews, source: :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_q

  def set_q
    @q = Item.ransack(params[:q])
    logger.debug('ここから')
    logger.debug(params[:q])
    logger.debug('ここまで')
    @items = @q.result
    if params[:q].present? && params[:q][:name_or_description_gt].present?
    @search_word = params[:q][:name_or_description_gt]
  end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def all_items
    @items = Item::where(category_id: params[:id])
    @category_name = Category.find(params[:id]).name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: %i(like_item)

  def show
    @item = Item.find(params[:id])
    @shops = @item.sales
  end

  def like_item
    user = current_user
    item = Item.find(params[:id])

    user.items << item
    redirect_to request.referer, notice: 'お気に入りに追加しました'
  end

  def remove_liked_item
    res = Like.where(item_id: params[:id]).find_by(user_id: current_user.id)
    res.destroy

    redirect_to request.referer, notice: 'お気に入りを解除しました'
  end

  def search
  end
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  def index
    @makers = Maker.all
  end

  def all_items
    @items = Item::where(maker_id: params[:id])
    @maker_name = Maker.find(params[:id]).name
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_item
  before_action :init_review

  def new
  end

  def create
    user = current_user
    item = Item.find(params[:id])

    @review = Review.new(review_params)
    @review.user_id = user.id
    @review.item_id = item.id

    if @review.save
      redirect_to show_item_path(item), notice: 'レビューを投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end


  # private
  def review_params
    params.require(:review).permit(:title, :body, :rate)
  end

  def find_item
    @item = Item.find(params[:id])
  end

  def init_review
    @review = Review.new
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "【価格.com】".freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{BASE_TITLE} - #{page_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def check_controller
    controller_name == 'home'
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def check_liked(item_id)
    item = Item.find(item_id)
    res = item.likes.where(user_id: current_user)

    res.any?
  end

  def get_star(rate)
    image_tag('ico_star_active.png', class: "ico") * rate
  end
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/all_items.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: @category_name + 'の製品一覧' } %>

<h2 class="basic-heading"><%= @category_name %></h2>

<ul class="item-list flex">
  <% @items.each do |item| %>
  <%= link_to show_item_path(item), class: 'contents' do %>
  <li class="item-list__item">
    <%= image_tag 'img_item.jpg' %>
    <h3 class="item-list__heading"><%= item.name %></h3>
    <p class="item-list__txt"><%= truncate(item.description, length:25) %></p>
  </li>
  <% end %>
  <% end %>
</ul>

app/views/items/search.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: @search_word } %>

<h2 class="basic-heading-blue"><%= @search_word %>の検索結果</h2>

<ul class="item-list flex">
  <% if @items.any? %>
  <% @items.each do |item| %>
  <%= link_to show_item_path(item), class: 'contents' do %>
  <li class="item-list__item">
    <%= image_tag 'img_item.jpg' %>
    <h3 class="item-list__heading"><%= item.name %></h3>
    <p class="item-list__txt"><%= truncate(item.description, length:25) %></p>
  </li>
  <% end %>
  <% end %>
  <% else %>
  <p>検索結果はありません</p>
  <% end %>
</ul>

app/views/items/show.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: @item.name } %>

<h2 class="basic-heading-light-blue"><%= @item.name %></h2>

<!-- flash message -->
<%= render 'shared/flash_message' %>

<!-- 商品詳細 -->
<div class="item-detail">
  <div class="item-detail__upper flex">
    <p class="item-detail__upper-before">
      <span>メーカー</span>&nbsp;<%= link_to @item.maker.name, all_items_by_maker_path(@item.maker), class: 'contents' %>
    </p>
    <p class="item-detail__upper-after">
      <%= @item.release_date.strftime('%Y年%m月%d日') %>&nbsp;発売
    </p>
  </div>
  <h3 class="item-detail__title"><%= @item.name %></h3>
  <% if check_liked(@item.id) %>
  <%= button_to remove_liked_item_path(@item), form_class: 'item-detail__form' do %>
  <%= image_tag 'ico_like.png', class: 'item-detail__form-ico', title: 'お気に入りを外す' %>
  <% end %>
  <% else %>
  <%= button_to like_item_path(@item), form_class: 'item-detail__form' do %>
  <%= image_tag 'ico_like.png', class: 'item-detail__form-ico', title: '商品をお気に入りに登録する' %>
  <% end %>
  <% end %>
  <span class="item-detail__txt">お気に入り登録(<%= @item.likes.size %>人)</span>
  <% if check_liked(@item.id) %>
  <span class="item-detail__label">登録済み</span>
  <% end %>
</div>

<!-- 店舗一覧 -->
<% if @shops.any? %>
<table class="item-shop">
  <caption class="item-shop__title"><%= @item.name %><span>(取扱店舗数:<%= @item.sales.size %>店舗)</span></caption>
  <thead>
    <tr>
      <th>価格（差額）</th>
      <th>送料</th>
      <th>在庫</th>
      <th>ショップ情報</th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
    <tr>
      <td class="price"><%= number_to_currency(shop.price) %></td>
      <td><%= shop.shop.postage %></td>
      <td><%= shop.shop.indication %></td>
      <td>
        <h3><%= shop.shop.name %></h3>
        <p><%= shop.shop.comment %></p>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p class="item-shop__txt">取扱店舗はありません</p>
<% end %>

<!-- レビュー一覧 -->
<div class="item-review">
  <h3 class="item-review__heading">ユーザーレビュー<span>～ユーザーから投稿された製品のレビュー評価～</span></h3>
  <div class="item-review__body">
    <p class="item-review__txt">
      この製品に投稿されたレビュー：<span><%= @item.reviews.size %></span>件
    </p>
    <% if @item.reviews.any? %>
    <% @item.reviews.each do |review| %>
    <div class="item-review__item">
      <div class="item-review__item-upper flex">
        <h4><span><%= review.user.name %></span>さん</h4>
        <p class="datetime"><%= review.created_at.strftime('%Y年%m月%d日 %H:%M') %></p>
        <p class="rate flex"><span>満足度</span><%= get_star(review.rate) %></p>
      </div>
      <div class="item-review__item-lower">
        <h4><%= review.title %></h4>
        <p><%= review.body %></p>
      </div>
    </div>
    <% end %>
    <% else %>
    <p>まだレビューはありません</p>
    <% end %>
    <hr class="item-review__line">
    <%= link_to 'レビューを投稿する', new_review_path(@item), class: 'item-review__link' %>
  </div>
</div>

app/views/makers/all_items.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: @maker_name + 'の製品一覧' } %>

<h2 class="basic-heading-blue"><%= @maker_name %></h2>

<ul class="item-list flex">
  <% @items.each do |item| %>
  <%= link_to show_item_path(item), class: 'contents' do %>
  <li class="item-list__item">
    <%= image_tag 'img_item.jpg' %>
    <h3 class="item-list__heading"><%= item.name %></h3>
    <p class="item-list__txt"><%= truncate(item.description, length:25) %></p>
  </li>
  <% end %>
  <% end %>
</ul>

app/views/makers/index.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: 'メーカー一覧' } %>

<h2 class="basic-heading-blue">メーカー一覧</h2>

<ul class="maker-list flex">
  <% @makers.each do |maker| %>
  <li class="maker-list__item">
    <%= link_to maker.name, all_items_by_maker_path(maker) %>
  </li>
  <% end %>
</ul>